name: b
seed: 18
learning_rate: 0.0000001
dataset_size: 10000
reload_interval: 5
dropout: 0.5
num_epochs: 7
batch_size: 64
vocab_size: 11117
embed_dim: 32
n_layers: 3
mask_prob: 0.35
mask_token: 11116
weight_decay: 0.0003
nhead: 4
use_weighted_loss: false
